"""Mathpix /v3/pdf async client: submit -> poll -> download."""
from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import requests
from PyQt6.QtCore import QThread, pyqtSignal

API_BASE = "https://api.mathpix.com/v3/pdf"

# Output extensions the API supports on GET /v3/pdf/{id}.{ext}
# Some are generated by default (mmd, lines.json, pdf overlay); others must
# be opted into via conversion_formats. Per Mathpix docs (post-v3-pdf), the
# accepted conversion_formats keys are: mmd, md, docx, tex.zip, html.
EXT_TO_KEY = {
    "mmd": None,           # always generated (Mathpix Markdown - LaTeX delimiters)
    "md": "md",             # standard Markdown - request via conversion_formats
    "docx": "docx",
    "tex.zip": "tex.zip",
    "html": "html",
    "lines.json": None,    # always generated
    "pdf": None,           # text-overlay PDF, always available
}


@dataclass
class PdfOptions:
    formats: tuple[str, ...] = ("mmd", "docx")
    page_ranges: str | None = None        # e.g. "2,4-6"
    rm_spaces: bool = True
    inline_delim: tuple[str, str] = ("$", "$")
    display_delim: tuple[str, str] = ("$$", "$$")


def _headers(app_id: str, app_key: str) -> dict[str, str]:
    return {"app_id": app_id, "app_key": app_key}


def submit_file(pdf_path: Path, opts: PdfOptions, app_id: str, app_key: str,
                timeout: int = 120) -> str:
    conversion = {opt: True for opt in opts.formats
                  if EXT_TO_KEY.get(opt) is not None}
    options_json: dict = {
        "math_inline_delimiters": list(opts.inline_delim),
        "math_display_delimiters": list(opts.display_delim),
        "rm_spaces": opts.rm_spaces,
    }
    if conversion:
        options_json["conversion_formats"] = conversion
    if opts.page_ranges:
        options_json["page_ranges"] = opts.page_ranges

    with open(pdf_path, "rb") as fh:
        resp = requests.post(
            API_BASE,
            headers=_headers(app_id, app_key),
            files={"file": (pdf_path.name, fh, "application/pdf")},
            data={"options_json": json.dumps(options_json)},
            timeout=timeout,
        )
    resp.raise_for_status()
    body = resp.json()
    if "error" in body:
        raise RuntimeError(f"Mathpix error: {body.get('error')}")
    pdf_id = body.get("pdf_id")
    if not pdf_id:
        raise RuntimeError(f"No pdf_id in response: {body}")
    return pdf_id


def get_status(pdf_id: str, app_id: str, app_key: str,
               timeout: int = 30) -> dict:
    resp = requests.get(f"{API_BASE}/{pdf_id}",
                        headers=_headers(app_id, app_key), timeout=timeout)
    resp.raise_for_status()
    return resp.json()


def download(pdf_id: str, ext: str, dest: Path, app_id: str, app_key: str,
             timeout: int = 120) -> None:
    """ext is one of: mmd, docx, tex.zip, html, lines.json, pdf"""
    with requests.get(f"{API_BASE}/{pdf_id}.{ext}",
                      headers=_headers(app_id, app_key),
                      timeout=timeout, stream=True) as resp:
        resp.raise_for_status()
        dest.parent.mkdir(parents=True, exist_ok=True)
        with open(dest, "wb") as fh:
            for chunk in resp.iter_content(chunk_size=64 * 1024):
                if chunk:
                    fh.write(chunk)


class PdfWorker(QThread):
    """Submit + poll + download all conversion formats."""

    progress = pyqtSignal(int, str)         # percent, status text
    log = pyqtSignal(str)                    # log line
    finished_ok = pyqtSignal(list, int)      # saved files, pages processed (0 = unknown)
    failed = pyqtSignal(str)

    POLL_INTERVAL_S = 2.0
    POLL_TIMEOUT_S = 600.0

    def __init__(self, pdf_path: Path, opts: PdfOptions, out_dir: Path,
                 app_id: str, app_key: str, parent=None):
        super().__init__(parent)
        self._pdf = pdf_path
        self._opts = opts
        self._out = out_dir
        self._id = app_id
        self._key = app_key
        self._cancel = False

    def cancel(self) -> None:
        self._cancel = True

    def run(self) -> None:
        try:
            self._do_run()
        except requests.HTTPError as exc:
            status = exc.response.status_code if exc.response is not None else "?"
            body = exc.response.text if exc.response is not None else ""
            self.failed.emit(f"HTTP {status}: {body[:300]}")
        except requests.RequestException as exc:
            self.failed.emit(f"Network error: {exc}")
        except Exception as exc:
            self.failed.emit(f"Unexpected: {exc}")

    def _do_run(self) -> None:
        self.log.emit(f"Uploading {self._pdf.name}...")
        pdf_id = submit_file(self._pdf, self._opts, self._id, self._key)
        self.log.emit(f"pdf_id = {pdf_id}")
        self.progress.emit(0, "Submitted, processing...")

        deadline = time.monotonic() + self.POLL_TIMEOUT_S
        last_status = ""
        num_pages = 0  # actual pages processed, per the status endpoint
        while True:
            if self._cancel:
                self.failed.emit("Cancelled by user")
                return
            if time.monotonic() > deadline:
                self.failed.emit("Polling timed out")
                return
            time.sleep(self.POLL_INTERVAL_S)
            try:
                status = get_status(pdf_id, self._id, self._key)
            except requests.RequestException as exc:
                self.log.emit(f"Poll failed (will retry): {exc}")
                continue
            st = status.get("status", "")
            pct = int(status.get("percent_done") or 0)
            done = status.get("num_pages_completed")
            total = status.get("num_pages")
            # Pages completed is the billable quantity (honors page_ranges);
            # fall back to the document total if it was never reported.
            if done:
                num_pages = int(done)
            elif total and not num_pages:
                num_pages = int(total)
            text = f"{st}: {done}/{total} pages" if total else st
            if text != last_status:
                self.progress.emit(pct, text)
                last_status = text
            if st == "completed":
                break
            if st == "error":
                self.failed.emit(f"Server reported error: {status}")
                return

        # Download each requested format
        out_dir = self._out
        out_dir.mkdir(parents=True, exist_ok=True)
        stem = self._pdf.stem
        saved: list[Path] = []
        for ext in self._opts.formats:
            if self._cancel:
                self.failed.emit("Cancelled by user")
                return
            self.log.emit(f"Downloading .{ext}...")
            dest = out_dir / f"{stem}.{ext}"
            download(pdf_id, ext, dest, self._id, self._key)
            self.log.emit(f"Saved {dest}")
            saved.append(dest)

        self.progress.emit(100, "Done")
        self.finished_ok.emit(saved, num_pages)
